Some improvements
aquasecurity/kube-query pull request #8
Opened 2019-11-26 00:45 UTC by simar7

This PR adds the following:

* .gitignore file
* go mod cleanup
* Improved documentation
* makefile
* go import cleanup

Signed-off-by: Simarpreet Singh <simar@linux.com>

2019-11-26 17:26 UTC, iyehuda requested changes

2019-11-26 17:29 UTC, lizrice requested changes
Probably best to keep the executable name as kube-query? I'm happy for pushback to kquery or kubequery if the hyphen looks strange in the context of osquery, but it would also need updating in the readme and maybe the project name too

2019-11-29 18:07 UTC, lizrice reviewed
looks good except for the question of the join, where I think @iYehuda's suggestion of UID is probably the right way to go

2019-11-29 20:51 UTC, iyehuda approved these changes
lgtm

2019-11-29 20:51 UTC, merged